#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'come on dog, provide a username'
    exit 1
fi

echo "creating user $1"

useradd $1
cd /home/$1
mkdir .ssh
cd .ssh
ssh-keygen -t rsa -b 1024 -C $1@aws -N '' -f /home/$1/.ssh/id_rsa <<< y
cat id_rsa.pub > authorized_keys
cat << EOF > /home/$1/.ssh/config
Host *
   StrictHostKeyChecking no
EOF
chmod 600 ./*
chmod 700 ../.ssh
chown -R $1:$1 ../.ssh
